// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transport.proto

package protoc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UploadFileReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	File                 []byte   `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadFileReq) Reset()         { *m = UploadFileReq{} }
func (m *UploadFileReq) String() string { return proto.CompactTextString(m) }
func (*UploadFileReq) ProtoMessage()    {}
func (*UploadFileReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{0}
}

func (m *UploadFileReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadFileReq.Unmarshal(m, b)
}
func (m *UploadFileReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadFileReq.Marshal(b, m, deterministic)
}
func (m *UploadFileReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadFileReq.Merge(m, src)
}
func (m *UploadFileReq) XXX_Size() int {
	return xxx_messageInfo_UploadFileReq.Size(m)
}
func (m *UploadFileReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadFileReq.DiscardUnknown(m)
}

var xxx_messageInfo_UploadFileReq proto.InternalMessageInfo

func (m *UploadFileReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UploadFileReq) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *UploadFileReq) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

type UploadFileResp struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadFileResp) Reset()         { *m = UploadFileResp{} }
func (m *UploadFileResp) String() string { return proto.CompactTextString(m) }
func (*UploadFileResp) ProtoMessage()    {}
func (*UploadFileResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{1}
}

func (m *UploadFileResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadFileResp.Unmarshal(m, b)
}
func (m *UploadFileResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadFileResp.Marshal(b, m, deterministic)
}
func (m *UploadFileResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadFileResp.Merge(m, src)
}
func (m *UploadFileResp) XXX_Size() int {
	return xxx_messageInfo_UploadFileResp.Size(m)
}
func (m *UploadFileResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadFileResp.DiscardUnknown(m)
}

var xxx_messageInfo_UploadFileResp proto.InternalMessageInfo

func (m *UploadFileResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DownloadFileReq struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Tag                  string   `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadFileReq) Reset()         { *m = DownloadFileReq{} }
func (m *DownloadFileReq) String() string { return proto.CompactTextString(m) }
func (*DownloadFileReq) ProtoMessage()    {}
func (*DownloadFileReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{2}
}

func (m *DownloadFileReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadFileReq.Unmarshal(m, b)
}
func (m *DownloadFileReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadFileReq.Marshal(b, m, deterministic)
}
func (m *DownloadFileReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadFileReq.Merge(m, src)
}
func (m *DownloadFileReq) XXX_Size() int {
	return xxx_messageInfo_DownloadFileReq.Size(m)
}
func (m *DownloadFileReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadFileReq.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadFileReq proto.InternalMessageInfo

func (m *DownloadFileReq) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *DownloadFileReq) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type DownloadFileResp struct {
	File                 []byte   `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadFileResp) Reset()         { *m = DownloadFileResp{} }
func (m *DownloadFileResp) String() string { return proto.CompactTextString(m) }
func (*DownloadFileResp) ProtoMessage()    {}
func (*DownloadFileResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a97e32c760ec1b28, []int{3}
}

func (m *DownloadFileResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadFileResp.Unmarshal(m, b)
}
func (m *DownloadFileResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadFileResp.Marshal(b, m, deterministic)
}
func (m *DownloadFileResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadFileResp.Merge(m, src)
}
func (m *DownloadFileResp) XXX_Size() int {
	return xxx_messageInfo_DownloadFileResp.Size(m)
}
func (m *DownloadFileResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadFileResp.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadFileResp proto.InternalMessageInfo

func (m *DownloadFileResp) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func init() {
	proto.RegisterType((*UploadFileReq)(nil), "transport.UploadFileReq")
	proto.RegisterType((*UploadFileResp)(nil), "transport.UploadFileResp")
	proto.RegisterType((*DownloadFileReq)(nil), "transport.DownloadFileReq")
	proto.RegisterType((*DownloadFileResp)(nil), "transport.DownloadFileResp")
}

func init() {
	proto.RegisterFile("transport.proto", fileDescriptor_a97e32c760ec1b28)
}

var fileDescriptor_a97e32c760ec1b28 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x29, 0x4a, 0xcc,
	0x2b, 0x2e, 0xc8, 0x2f, 0x2a, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0x79, 0x72, 0xf1, 0x86, 0x16, 0xe4, 0xe4, 0x27, 0xa6, 0xb8, 0x65, 0xe6, 0xa4, 0x06, 0xa5, 0x16,
	0x0a, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81,
	0xd9, 0x42, 0x02, 0x5c, 0xcc, 0x25, 0x89, 0xe9, 0x12, 0x4c, 0x60, 0x21, 0x10, 0x13, 0xa4, 0x2a,
	0x2d, 0x33, 0x27, 0x55, 0x82, 0x59, 0x81, 0x51, 0x83, 0x27, 0x08, 0xcc, 0x56, 0xd2, 0xe2, 0xe2,
	0x43, 0x36, 0xaa, 0xb8, 0x40, 0x48, 0x82, 0x8b, 0x3d, 0x37, 0xb5, 0xb8, 0x38, 0x31, 0x1d, 0x66,
	0x1c, 0x8c, 0xab, 0x64, 0xce, 0xc5, 0xef, 0x92, 0x5f, 0x9e, 0x87, 0x66, 0x71, 0x41, 0x62, 0x49,
	0x06, 0xcc, 0x62, 0x10, 0x1b, 0xd3, 0x62, 0x25, 0x35, 0x2e, 0x01, 0x54, 0x8d, 0xc5, 0x05, 0x70,
	0xc7, 0x30, 0x22, 0x1c, 0x63, 0x34, 0x8f, 0x91, 0x8b, 0x0d, 0xe2, 0x1a, 0x21, 0x77, 0x2e, 0x2e,
	0x84, 0xbb, 0x84, 0x24, 0xf4, 0x10, 0xa1, 0x81, 0xe2, 0x73, 0x29, 0x49, 0x1c, 0x32, 0xc5, 0x05,
	0x4a, 0x0c, 0x1a, 0x8c, 0x06, 0x8c, 0x42, 0xde, 0x5c, 0x5c, 0x2e, 0xf9, 0x70, 0x83, 0xa4, 0x90,
	0x94, 0xa3, 0xf9, 0x45, 0x4a, 0x1a, 0xa7, 0x1c, 0xcc, 0xb0, 0x24, 0x36, 0x70, 0x54, 0x18, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x3c, 0x66, 0xef, 0x9d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UploadClient is the client API for Upload service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UploadClient interface {
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (Upload_UploadFileClient, error)
	DoloadFile(ctx context.Context, opts ...grpc.CallOption) (Upload_DoloadFileClient, error)
}

type uploadClient struct {
	cc grpc.ClientConnInterface
}

func NewUploadClient(cc grpc.ClientConnInterface) UploadClient {
	return &uploadClient{cc}
}

func (c *uploadClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (Upload_UploadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Upload_serviceDesc.Streams[0], "/transport.Upload/UploadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &uploadUploadFileClient{stream}
	return x, nil
}

type Upload_UploadFileClient interface {
	Send(*UploadFileReq) error
	Recv() (*UploadFileResp, error)
	grpc.ClientStream
}

type uploadUploadFileClient struct {
	grpc.ClientStream
}

func (x *uploadUploadFileClient) Send(m *UploadFileReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *uploadUploadFileClient) Recv() (*UploadFileResp, error) {
	m := new(UploadFileResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *uploadClient) DoloadFile(ctx context.Context, opts ...grpc.CallOption) (Upload_DoloadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Upload_serviceDesc.Streams[1], "/transport.Upload/DoloadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &uploadDoloadFileClient{stream}
	return x, nil
}

type Upload_DoloadFileClient interface {
	Send(*DownloadFileReq) error
	Recv() (*DownloadFileResp, error)
	grpc.ClientStream
}

type uploadDoloadFileClient struct {
	grpc.ClientStream
}

func (x *uploadDoloadFileClient) Send(m *DownloadFileReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *uploadDoloadFileClient) Recv() (*DownloadFileResp, error) {
	m := new(DownloadFileResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UploadServer is the server API for Upload service.
type UploadServer interface {
	UploadFile(Upload_UploadFileServer) error
	DoloadFile(Upload_DoloadFileServer) error
}

// UnimplementedUploadServer can be embedded to have forward compatible implementations.
type UnimplementedUploadServer struct {
}

func (*UnimplementedUploadServer) UploadFile(srv Upload_UploadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (*UnimplementedUploadServer) DoloadFile(srv Upload_DoloadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method DoloadFile not implemented")
}

func RegisterUploadServer(s *grpc.Server, srv UploadServer) {
	s.RegisterService(&_Upload_serviceDesc, srv)
}

func _Upload_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UploadServer).UploadFile(&uploadUploadFileServer{stream})
}

type Upload_UploadFileServer interface {
	Send(*UploadFileResp) error
	Recv() (*UploadFileReq, error)
	grpc.ServerStream
}

type uploadUploadFileServer struct {
	grpc.ServerStream
}

func (x *uploadUploadFileServer) Send(m *UploadFileResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *uploadUploadFileServer) Recv() (*UploadFileReq, error) {
	m := new(UploadFileReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Upload_DoloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UploadServer).DoloadFile(&uploadDoloadFileServer{stream})
}

type Upload_DoloadFileServer interface {
	Send(*DownloadFileResp) error
	Recv() (*DownloadFileReq, error)
	grpc.ServerStream
}

type uploadDoloadFileServer struct {
	grpc.ServerStream
}

func (x *uploadDoloadFileServer) Send(m *DownloadFileResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *uploadDoloadFileServer) Recv() (*DownloadFileReq, error) {
	m := new(DownloadFileReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Upload_serviceDesc = grpc.ServiceDesc{
	ServiceName: "transport.Upload",
	HandlerType: (*UploadServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFile",
			Handler:       _Upload_UploadFile_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "DoloadFile",
			Handler:       _Upload_DoloadFile_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "transport.proto",
}
